export const env = {
  SUPABASE_URL:      process.env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  RESEND_API_KEY:    process.env.RESEND_API_KEY!,
  BACKEND_API_URL:   process.env.BACKEND_API_URL!,
  SITE_URL:          process.env.NEXT_PUBLIC_SITE_URL!,
};